# SPDX-FileCopyrightText: © 2024 Rajul Jha <rajuljha49@gmail.com>
#
# SPDX-License-Identifier: GPL-2.0-only
name: Test Fossology Action
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        with:
          scan_mode: "repo"
          scanners: "nomos ojo copyright keyword"
          report_format: "SPDX_JSON"
